name: Run SQL Server in GitHub Actions

on: [push]

jobs:
  test-sql:
    runs-on: ubuntu-latest  # Uses GitHub-hosted runner with pre-installed Docker
    
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Siyakhanya@2002"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "sqlcmd -S localhost -U Auto_user1 -P Siyakhanya@2002 -Q 'SELECT 1'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Wait for SQL Server to Start
        run: |
          sleep 20s
          sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q "SELECT @@VERSION"

      - name: Run SQL Script
        run: |
          sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -i CreateDatabaseAndTable.sql

