name: MS Teams Notification
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Send Teams Notification
        uses: skitionek/notify-msteams@v1
        if: always()
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          message: |
            ${{ github.event.pull_request.merged == true && 'The pull request was successfully merged.' || 'The request was not merged.' }}
