name: Deploy SQL Database and Table 

on:
  push:
    branches:
      - main
    paths:
      - 'Database/**'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Ubuntu runner

    steps:
      # Step 1: Checkout the repository to access the SQL script
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Confirm checkout
        run: |
         echo "Step 1: Checked out the repository containing setup.sql"
      # Step 2: Install Microsoft SQL Server tools (sqlcmd)
      - name: Install sqlcmd
        run: |
          echo "Step 2: Installing sqlcmd on Ubuntu"
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo "/opt/mssql-tools/bin" >> $GITHUB_PATH
          echo "sqlcmd version: $(sqlcmd -? | grep Version)"
          echo "Step 2 completed: sqlcmd installed"
      # Step 3: Deploy database, table, stored procedure, and data
      - name: Deploy SQL database and table
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }} 
          SQL_USER: testuser
          SQL_PASS: ${{ secrets.SQL_PASS }}  
        run: |
          echo "Step 3: Running setup1.sql"
          sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASS" -i Database/setup.sql -l 60
          echo "Step 3 completed: SQL script executed"
      # Step 4: Verify deployment by querying the table
      - name: Verify deployment
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: testuser
          SQL_PASS: ${{ secrets.SQL_PASS }}
        run: |
          echo "Step 4: Verifying data in user table"
          sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASS" -Q "USE AutoTest; SELECT * FROM [user];" -l 60
          echo "Step 4 completed: Verified data in user table"
